### PR TITLE
Better adoption for 3rd party S3 services

### LINKED ISSUE #2: Does not work with custom S3 compatible hosts
Seems to be hardcoded to AWS specific config

### PR DESCRIPTION
**Pull request by yikerman**
Fixes #2. I've only tested Cloudflare R2.

- Add `endpoint` in the setting, which should be the base URL that is given by the 3rd party S3-compatible storage.
- Removed the 20 char limit on `accessKeyId`.
- Got rid of the confusing `AWS.config.update`. All params are passed upon creating the `S3` object.
  - The `S3Conn` singleton is removed too. Constructing a S3 object is a light task and shouldn't have any noticeable impact on performance.
- Bumped version number from `3.0.5` to `3.0.6`

### CODE REVIEW

**Comment by barisusakli** [comment]
@xiaoyu2006 you can just remove the unused code instead of commenting it out.

**Comment by yikerman** [comment]
Sure. I was kind of unsure if this will be accepted.

**Comment by yikerman** [comment]
@barisusakli Done.

**Comment by barisusakli** [comment]
So `settings.region` isn't used at all now? Should we make that a input in the ACP page as well?

**Comment by yikerman** [comment]
According to [Cloudflare's example](https://developers.cloudflare.com/r2/api/s3/api/#bucket-region) (I am not an AWS expert, and this was what I was referring to), region is mandatory in sdk v3. In the current situation, however, we are still stuck at v2 and region is supplied by endpoint. I haven't tested it on AWS so I'm not sure if this is fine too.

Honestly the AWS API wasn't designed with 3rd party in mind.

**Comment by yikerman** [comment]
@barisusakli `aws-sdk` is now updated to the recommended v3 in which region is mandatory. `region` setting is now no longer a select but a normal string.

**Pull request merged**
